### ISSUE TITLE
Little suggestion

### ISSUE THREAD

**Issue by darkdarcool** [BD103/java-quickstart#1]
I know a bit about Java, so this all makes sense to me. But for a starting dev who knows nothing about programming in general, I would say make thing ***REALLY*** verbose! Doesn't matter how long it is! (in fact, the longer the better). Not saying it isn't verbose right now, but make sure it is really verbose!

Hope this helps!

**Comment by BD103** [comment]
By verbose, do you mean like explaining what I'm trying to explain by doing the thing called explaining with lots of words like explain and explanation and "give a reason for"?

Seriously, though. Any suggestions? (PRs also work!)

**Comment by darkdarcool** [comment]
> By verbose, do you mean like explaining what I'm trying to explain by doing the thing called explaining with lots of words like explain and explanation and "give a reason for"?
> 
> Seriously, though. Any suggestions? (PRs also work!)

Yup! Someone who has absolutely no programming knowledge should walk away with basic Java knowledge and the skill to write a basic Java program.

And on suggestion would also be to make popular module explanations (like Java swing,  etc.)

**Comment by BD103** [comment]
Got it! The main page (README) is generic Java, there may be other pages for other stuff though. I'll keep open for now, thanks!

**Comment by darkdarcool** [comment]
Yup! Not saying you should copy, but take a look at the Airbnb JS style guide. They have a bunch of things, not just JS, like react, css in react, etc. Which I find nice.
